import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { build } from 'esbuild';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.resolve(__dirname, '..');

// Konfigurasi Jalur Folder Terpusat
const PATHS = {
  coreDist: 'packages/stria-icons-core/dist',
  reactPackage: 'packages/stria-icons-react'
};

const CORE_DIST_DIR = path.join(ROOT_DIR, PATHS.coreDist);
const REACT_DIR = path.join(ROOT_DIR, PATHS.reactPackage);
const REACT_SRC_DIR = path.join(REACT_DIR, 'src');

async function exists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

// Convert kebab-case to PascalCase (e.g. chevron-right -> ChevronRight)
function toPascalCase(str) {
  return str
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

// Extract path data from SVG content
function extractPathData(svgContent) {
  const matches = [...svgContent.matchAll(/<path[^>]*d="([^"]+)"/g)];
  return matches.map(m => m[1]);
}

// Extract viewBox from SVG content
function extractViewBox(svgContent) {
  const match = svgContent.match(/viewBox="([^"]+)"/);
  return match ? match[1] : '0 0 24 24';
}

async function run() {
  console.log('Building React package wrappers...');
  
  const catalogPath = path.join(CORE_DIST_DIR, 'icons.json');
  if (!(await exists(catalogPath))) {
    console.error(`Core catalog icons.json not found in ${PATHS.coreDist}. Run build-core first.`);
    process.exit(1);
  }
  
  const catalog = JSON.parse(await fs.readFile(catalogPath, 'utf8'));
  const STYLES = ['solid', 'regular', 'light', 'thin', 'duotone', 'brands'];
  
  await fs.mkdir(REACT_SRC_DIR, { recursive: true });
  
  const barrelExports = [];
  
  for (const style of STYLES) {
    const styleSrcDir = path.join(REACT_SRC_DIR, 'icons', style);
    await fs.mkdir(styleSrcDir, { recursive: true });
    
    const svgStyleDir = path.join(CORE_DIST_DIR, 'svg', style);
    if (!(await exists(svgStyleDir))) continue;
    
    const files = await fs.readdir(svgStyleDir);
    for (const file of files) {
      if (file.endsWith('.svg')) {
        const name = path.basename(file, '.svg');
        const pascalName = toPascalCase(name);
        
        // Suffix styling to avoid exports naming clashes in barrel file
        // e.g. UserSolid, UserRegular, UserLight, etc.
        let componentName = `${pascalName}${toPascalCase(style)}`;
        if (/^\d/.test(componentName)) {
          componentName = `Icon${componentName}`;
        }
        
        const svgContent = await fs.readFile(path.join(svgStyleDir, file), 'utf8');
        const paths = extractPathData(svgContent);
        const viewBox = extractViewBox(svgContent);
        
        let pathElements = '';
        paths.forEach((p, index) => {
          if (style === 'duotone' && index === 0) {
            pathElements += `    <path d="${p}" className="stria-secondary" style={{ opacity: 0.4 }} />\n`;
          } else {
            pathElements += `    <path d="${p}" />\n`;
          }
        });
        
        const componentCode = `import React, { forwardRef } from 'react';

const ${componentName} = forwardRef(({ size = 24, color = 'currentColor', className, ...props }, ref) => (
  <svg
    ref={ref}
    xmlns="http://www.w3.org/2000/svg"
    width={size}
    height={size}
    viewBox="${viewBox}"
    fill={color}
    className={className}
    {...props}
  >
${pathElements}  </svg>
));

${componentName}.displayName = '${componentName}';

export default ${componentName};
`;
        
        const componentFile = path.join(styleSrcDir, `${pascalName}.jsx`);
        await fs.writeFile(componentFile, componentCode, 'utf8');
        
        barrelExports.push({
          componentName,
          style,
          pascalName,
          importPath: `./icons/${style}/${pascalName}.jsx`
        });
      }
    }
  }
  
  // Write barrel file (src/index.js)
  let indexCode = `/* Auto-generated by Stria React Wrapper compiler */\n\n`;
  barrelExports.forEach(exp => {
    indexCode += `export { default as ${exp.componentName} } from '${exp.importPath}';\n`;
  });
  
  const barrelFile = path.join(REACT_SRC_DIR, 'index.js');
  await fs.writeFile(barrelFile, indexCode, 'utf8');
  
  // Also write basic type definition (src/index.d.ts)
  let dtsCode = `import { ForwardRefExoticComponent, SVGProps, RefAttributes } from 'react';

export interface IconProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
  color?: string;
}

export type IconComponent = ForwardRefExoticComponent<IconProps & RefAttributes<SVGSVGElement>>;
\n`;
  barrelExports.forEach(exp => {
    dtsCode += `export declare const ${exp.componentName}: IconComponent;\n`;
  });
  
  const dtsFile = path.join(REACT_SRC_DIR, 'index.d.ts');
  await fs.writeFile(dtsFile, dtsCode, 'utf8');

  // Bundle with esbuild
  console.log('Bundling React components with esbuild...');
  const distDir = path.join(REACT_DIR, 'dist');
  await fs.mkdir(path.join(distDir, 'esm'), { recursive: true });
  await fs.mkdir(path.join(distDir, 'cjs'), { recursive: true });
  await fs.mkdir(path.join(distDir, 'types'), { recursive: true });

  // ESM Build
  await build({
    entryPoints: [barrelFile],
    bundle: true,
    minify: true,
    format: 'esm',
    outfile: path.join(distDir, 'esm/index.mjs'),
    external: ['react'],
    banner: {
      js: "import * as React from 'react';",
    },
  });

  // CommonJS Build
  await build({
    entryPoints: [barrelFile],
    bundle: true,
    minify: true,
    format: 'cjs',
    outfile: path.join(distDir, 'cjs/index.cjs'),
    external: ['react'],
    banner: {
      js: "var React = require('react');",
    },
  });

  // Copy type definitions to dist
  await fs.writeFile(path.join(distDir, 'types/index.d.ts'), dtsCode, 'utf8');

  // Copy LICENSE, LICENSE-ICONS, and README.md to packages/react/
  const rootFiles = ['LICENSE', 'LICENSE-ICONS', 'README.md'];
  for (const f of rootFiles) {
    const srcPath = path.resolve(f);
    const destPath = path.join(REACT_DIR, f);
    if (await exists(srcPath)) {
      await fs.copyFile(srcPath, destPath);
    }
  }
  
  console.log(`React package wrappers generated and bundled successfully. Total components: ${barrelExports.length}`);
}

run().catch(err => {
  console.error('Error building React wrappers:', err);
  process.exit(1);
});
